feynman/config/routes.rb
Feynman::Application.routes.draw do
  # devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       # :registrations => "registrations" }
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users, :only => [:show]
  resources :events, :only => [:create, :index, :new]
  resources :user_details, :only => [:edit, :update]
  resources :authentications, :only => [:new]
  resources :deals, :only => [:index]

  resources :signups, :only => [:new, :create] do
    collection do
      get  :preferences
      post :save_preferences
      post :personal_details
      post :save_personal_details
    end
  end
  
  resources :messages, :only => [:index, :show]
    
  namespace :api do
    namespace :v1 do
      resources :authentications, :only => [:index]
      resources :messages, :only => [:index, :show, :create]
      resources :events, :only => [:index, :create, :update]
      resources :images, :only => [:create, :index]
      resources :deals, :only => [:index]
      match 'user_details/jeditable/:id' => 'user_details#jeditable', :as => 'jeditable', :via => :put
      resources :user_details, :only => [:update]
      resources :user_validators, :only => [:create]
    end
  end

  match '/profile/:slug' => 'users#show', :as => 'profile'
  root to: 'pages#index'
end

feynman/app/views/layouts/_footer.html.erb
<div class="row">
<footer class="span12">
  <ul>
  <li>&copy;dailydates 2012</li>
  <li><%= link_to "Support", "/support" %></li>
  <li><%= link_to "Terms of Service", "/tos" %></li>
  </ul>
</footer class="span12">
</div>

feynman/app/views/layouts/_header.html.erb
<div class="container-fluid">
  <div id="alert-bar" class="span10" style="display: none"></div>
</div>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">daily<span>dates</span></a>
      <div class="container nav-collapse">
        <ul class="nav">
          <li><%= link_to "Find a Date", events_path %></li>
          <li><%= link_to "Post a Date", new_event_path %></li>
          <% if current_user %>
          <li><%= link_to "Messages (#{current_user.unread_messages_count})", messages_path %></li>
            <li class="dropdown"><%= render "layouts/nav_login" %></li>
          <% else %>
            <li><%= link_to "Log in", new_user_session_path %></li>
          <% end %>
          <li class="dropdown" id="menu1">
        </ul>
      </div><!--/.nav-collapse -->
      <% if current_user %>
        <%= content_tag "div", class: "user_meta", data: { id: current_user.id, token: current_user.authentication_token, location: @location } do %><% end %>
      <% end %>
    </div>
  </div>
</div>

feynman/app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

feynman/app/views/layouts/_nav_login.html.erb
<a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b></a>
<ul class="dropdown-menu">
  <li><%= link_to "Profile", profile_path(current_user.display_name) if current_user.display_name %></li>
  <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
</ul>

feynman/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "DailyDate" %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <script type="text/javascript" src="http://use.typekit.com/qgy6neb.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
    <link rel="shortcut icon" type="image/png" href="/assets/edweng.ico" />
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if location == "splash" %>
    <% else %>
      <%= render "layouts/header" %>
    <% end %>
    <div id="main_content" class="container-fluid">
      <div id="app" class="content">
        <div id="flash"></div>
        <%= yield %>
      </div><!--/content-->
      <!--<%= render "layouts/footer" %>-->
    </div> <!-- /container -->
  </body>
</html>