feynman/config/routes.rb
Feynman::Application.routes.draw do
  # devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       # :registrations => "registrations" }
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users, :only => [:show]
  resources :events, :only => [:create, :index, :new]
  resources :user_details, :only => [:edit, :update]
  resources :authentications, :only => [:new]
  resources :deals, :only => [:index]

  resources :signups, :only => [:new, :create] do
    collection do
      get  :preferences
      post :save_preferences
      post :personal_details
      post :save_personal_details
    end
  end
  
  resources :messages, :only => [:index, :show]
    
  namespace :api do
    namespace :v1 do
      resources :authentications, :only => [:index]
      resources :messages, :only => [:index, :show, :create]
      resources :events, :only => [:index, :create, :update]
      resources :images, :only => [:create, :index]
      resources :deals, :only => [:index]
      match 'user_details/jeditable/:id' => 'user_details#jeditable', :as => 'jeditable', :via => :put
      resources :user_details, :only => [:update]
      resources :user_validators, :only => [:create]
    end
  end

  match '/profile/:slug' => 'users#show', :as => 'profile'
  root to: 'pages#index'
end

feynman/app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  def create
    user_preferences = JSON.parse(params[:user].delete(:user_preferences))
    @user = User.new(params[:user])

    if @user.valid?
      @user = User.create_user_with_detail(params[:user], user_preferences)
      sign_in(:user, @user)
      redirect_to profile_path(@user.slug), :notice => "You have successfully signed up."
    else
      @user_preferences = user_preferences.to_json
      render 'personal_details'
    end
  end
end

feynman/app/views/signups/_personal_details_form.html.erb
    <div class="control-group">
      <%= user.label :birthday, :class => "control-label" %>
      <div class="controls">
        <%= user.date_select(:birthday, { :order => [:month, :day, :year], :start_year => Time.now.year, :end_year => 1913, :default => {:year => 1994} }, {:class => "birthday"} ) %>
      </div>
    </div>
    <div class="control-group">
      <%= user.label :display_name, :class => "control-label" %>
      <div class="controls">
        <%= user.text_field :display_name %>
      </div>
    </div>
    <div class="control-group">
      <%= user.label :email, :class => "control-label" %>
      <div class="controls">
        <%= user.text_field :email %> 
      </div>
    </div>
    <div class="control-group">
      <%= user.label :password, :class => "control-label" %>
      <div class="controls">
        <%= user.password_field :password %> 
      </div>
    </div>
    <%= user.hidden_field :user_preferences, :value => @user_preferences %>
    <p><%= user.submit "Back", { :name => "back_button", :class => "btn btn-primary btn-large", :id => "signup_back" } %>
  <%= user.submit "Continue", { :class => "btn btn-primary btn-large", :id => "submit_new_user" } %></p>

feynman/app/views/signups/_preferences_form.html.erb
  <p class="signup_form">I'm a 
    <%= u.select(:gender, %w(male female), { :selected => "female", :index => nil }, {:class => 'gender'}) %> 
    interested in 
    <%= u.select(:gender_preference, %w(men women both), { :selected => "men", :index => nil }, {:class => 'gender'}) %>
  </p>
  <p class="signup_form">
    between
    <%= u.text_field :age_range_lower, { :class => "age", :placeholder => "25" } %> 
    and 
    <%= u.text_field :age_range_upper, { :class => "age", :placeholder => "35" } %> 
    near 
    <%= u.text_field :zipcode, { :class => "zip", :placeholder => "zip" } %>
  </p>
  <div class="row-fluid">
    <p><%= u.submit "Continue", { :class => "btn btn-primary btn-large", :id => "signup_continue" } %></p>
  </div>

feynman/app/views/signups/personal_details.html.erb
<p class="signup_form">
  <%= form_for @user, :url => signups_path, :html => {:class => "form-horizontal"} do |user| %>
    <%= render "shared/form_errors", :object => @user %>
    <%= render "personal_details_form", :user => user %>
  <% end %>

</p>

feynman/app/views/signups/preferences.html.erb
<%= form_for @user_detail, :url => save_preferences_signups_path, :html => {:class => "form-horizontal"} do |u| %>
  <%= render "shared/form_errors", :object => @user_detail %>
  <%= render "preferences_form", :u => u %>
<% end %>